### ISSUE TITLE
Source Code unavailable 🥺

### ISSUE THREAD

**Issue by Lakhankumawat** [JohannesMilke/persistent_bottom_sheet_example#1]
# 1. I Requested for source code [here](https://johannesmilke.com/#/request)

![asdd](https://user-images.githubusercontent.com/55774240/138734527-8fb22e5b-a463-441d-a6a0-08a0671cc8db.png)

# 2. Button Confirm your Subscription is not working or unclickable
![asfd](https://user-images.githubusercontent.com/55774240/138734535-6448bbef-de5b-43f4-91d0-42cea97ccaf2.png)

**Comment by kitoheedong** [comment]
I am having the same issue. I am already sponsoring @JohannesMilke.
Please check it.

**Comment by JohannesMilke** [comment]
> heedongrichrich

Simply accept the invitation sent to you via GitHub:  https://github.com/orgs/JohannesMilke-Sponsors/invitation?via_email=1

**Comment by JohannesMilke** [comment]
> I am having the same issue. I am already sponsoring @JohannesMilke. Please check it.

@heedongrichrich Simply accept the invitation sent to you via GitHub:  https://github.com/orgs/JohannesMilke-Sponsors/invitation?via_email=1

**Comment by kitoheedong** [comment]
> > I am having the same issue. I am already sponsoring @JohannesMilke. Please check it.
> 
> @heedongrichrich Simply accept the invitation sent to you via GitHub: https://github.com/orgs/JohannesMilke-Sponsors/invitation?via_email=1

Thank you so much for fast response. Now I can get access to the all the code!

**Comment by Lakhankumawat** [comment]
It says invitation not found after clicking the link . 
Also I don't need source code anymore thanks for your efforts thought , please fix this source code static website so that newcomers like me don't face any issues after following your tutorials .
